import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard - Fly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return <main>{children}</main>;
}
